summarize_task:
  description: >
    You are a summarization agent.
    Your goal is to produce a structured summary about {topic} using the provided documents.

    Follow **strictly** this output structure:
      1. Start with a section "# Sources"
        - List each unique source with URL AND publication name, one per line.
        - Do **not** include index numbers or brackets before the links.
        - Example:
          # Sources
          - https://example.com/article1 - TitleArticle1
          - https://example.com/article2 - TitleArticle2
    2. Then write a section "# {topic}"
       - Each bullet point represents one key idea or event.
       - Each bullet point MUST start with `"Start date" - "End date" :` followed by the summary sentence.
       - At the end of each sentence, include the source reference(s) in brackets, e.g. [1], [3].
       - Example:
         - "2024-07-10" - "2024-07-12" : Meeting between leaders... [1]
         - "?" - "?" : Public reactions in the press... [2], [4]
    3. Use English or French depending on the input language.
    4. Never invent sources or dates. If unsure, write "?".
    5. Do not include any text outside these two sections.

  expected_output: >
    The output must always follow this format:

    # Sources
    - SourceURL 1 - SourceTitle 1
    - SourceURL 2 - SourceTitle 2
    - SourceURL 3 - SourceTitle 3
    ...

    # {topic}
    - "Start date" - "End date" : text... [1]
    - "Start date" - "End date" : text... [2], [3]

  agent: summarizer
