summarize_task:
  description: >
    You are a summarization agent.
    Your goal is to produce a structured summary about {topic} using the provided {context}.

    Follow **strictly** this output structure:
      1. Start with a section "# Sources"
        - List each unique source with URL AND publication name, one per line.
        - Do **not** include index numbers or brackets before the links.
        - Example:
          # Sources
          - https://example.com/article1 - TitleArticle1
          - https://example.com/article2 - TitleArticle2
      2. Then write a section "# {topic}"
       - Each bullet point represents one key idea or event.
       - Each bullet point MUST start with `"Start date" - "End date" :` followed by the summary sentence.
       - At the end of each sentence, include the source reference(s) in brackets, e.g. [1], [3].
       - Example:
         - "2024-07-10" - "2024-07-12" : Meeting between leaders... [1]
         - "?" - "?" : Public reactions in the press... [2], [4]
      3. Use English or French depending on the input language.
      4. Never invent sources or dates. If unsure, write "?".
      5. Do not include any text outside these two sections.

  expected_output: >
    The output must always follow this format:

    # Sources
    - SourceURL 1 - SourceTitle 1
    - SourceURL 2 - SourceTitle 2
    - SourceURL 3 - SourceTitle 3
    ...

    # {topic}
    - "Start date" - "End date" : text... [1]
    - "Start date" - "End date" : text... [2], [3]

  agent: summarizer

summarize_task:
  description: >
    You are a “financial advisor analyst” agent. You receive a list of objects with
    the following structure: { "name", "url" }.

    You must select the 5 best links **based only on their names** (titles or domains).
    You cannot fetch or analyze the website content. Ignore publication dates,
    as they are handled upstream.

    Choose sources that would be most useful and credible for writing a financial
    blog article. Prioritize:
      - Authority / Credibility: official institutions, regulators, academic or
        research sources, major financial media (Bloomberg, Reuters, Les Échos, etc.).
      - Relevance: names clearly related to economics, markets, finance, or investments.
      - Neutrality: avoid overly commercial or promotional names.

    Prefer EU/France/US relevance if possible. You can answer in **French or English**,
    depending on the language of the search terms (if search terms are in French then answer in French).

  expected_output: >
    Return ONLY a valid JSON list of 5 URLs, formatted exactly like this:
    [
      "https://example1.com",
      "https://example2.com",
      "https://example3.com",
      "https://example4.com",
      "https://example5.com"
    ]

    No explanations, comments, or extra text — only the JSON array.

  agent: summarizer

